import { useState } from 'react';
import { useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ScrollView, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Body, Button, C, Card, Eyebrow, H1, H2, Page, Pill } from '@/components/ui';
import { OPERATORS } from '@/data/operators';
import { EPISODE_DOMAINS, EpisodeDomain, makeEpisodeId, saveEpisode } from '@/lib/episodes';

export default function Checkin(){const router=useRouter();const [operator,setOperator]=useState<number|null>(null);const [domain,setDomain]=useState<EpisodeDomain>('Other');const [note,setNote]=useState('');const [saved,setSaved]=useState(false);
 const save=async()=>{if(!operator)return;const op=OPERATORS[operator-1];await saveEpisode({id:makeEpisodeId(),createdAt:new Date().toISOString(),condition:`Daily check-in · ${domain}`,object:'Situation noticed today',action:note.trim()||`Observed ${op.verb}`,transformation:op.movement,result:'Quick check-in; expand later if useful.',operator,competingOperator:null,confidence:3,domain,testedOperator:null,evidenceEffect:'ambiguous',note:note.trim()});setSaved(true);};
 if(saved)return <SafeAreaView style={{flex:1,backgroundColor:C.bg}}><Page style={{justifyContent:'center'}}><Pill label="ANAMNESIS SAVED" tone="success"/><H1>One observation is a datum. Repetition becomes a pattern.</H1><Body muted>Your check-in is now part of the longitudinal record. Do not force the next episode to agree with it.</Body><Button label="Open Anamnesis record" onPress={()=>router.replace('/episodes')}/><Button secondary label="Return home" onPress={()=>router.replace('/')}/></Page></SafeAreaView>;
 return <SafeAreaView style={{flex:1,backgroundColor:C.bg}}><ScrollView><Page>
 <Eyebrow>QUICK ANAMNESIS</Eyebrow><H1>What operation did you actually witness today?</H1><Body muted>A 60-second record for lived behavior. For a rigorous five-slot episode, use the full recorder afterward.</Body>
 <Card><Eyebrow>1 · DOMAIN</Eyebrow><View style={s.wrap}>{EPISODE_DOMAINS.map(d=><Pressable key={d} onPress={()=>setDomain(d)} style={[s.chip,domain===d&&s.chipOn]}><Text style={[s.chipText,domain===d&&s.chipTextOn]}>{d}</Text></Pressable>)}</View></Card>
 <Card><Eyebrow>2 · OPERATOR</Eyebrow><View style={s.ops}>{OPERATORS.map(o=><Pressable key={o.n} onPress={()=>setOperator(o.n)} style={[s.op,operator===o.n&&s.opOn]}><Text style={[s.opN,operator===o.n&&{color:'#E8C96F'}]}>{o.n}</Text><Text style={[s.opV,operator===o.n&&{color:C.white}]}>{o.verb}</Text></Pressable>)}</View></Card>
 <Card><Eyebrow>3 · WHAT HAPPENED?</Eyebrow><TextInput multiline value={note} onChangeText={setNote} placeholder="One concrete sentence. What was done, crossed, tested, restored, amplified…?" placeholderTextColor={C.muted} style={s.input}/></Card>
 <Button label={operator?'Save quick check-in':'Choose an operator first'} disabled={!operator} onPress={save}/><Button secondary label="Use full five-slot episode recorder" onPress={()=>router.push('/episode')}/>
 </Page></ScrollView></SafeAreaView>}
const s=StyleSheet.create({wrap:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{paddingHorizontal:10,paddingVertical:7,borderRadius:999,borderWidth:1,borderColor:C.line,backgroundColor:C.white},chipOn:{backgroundColor:C.tealSoft,borderColor:C.teal},chipText:{fontSize:12,fontWeight:'700',color:C.muted},chipTextOn:{color:C.teal},ops:{gap:7},op:{flexDirection:'row',alignItems:'center',gap:10,borderWidth:1,borderColor:C.line,borderRadius:15,padding:11,backgroundColor:C.white},opOn:{backgroundColor:C.lapis2,borderColor:C.lapis2},opN:{fontSize:19,fontWeight:'900',color:C.gold,width:24},opV:{fontSize:12,fontWeight:'900',letterSpacing:1,color:C.ink},input:{minHeight:110,textAlignVertical:'top',fontSize:15,lineHeight:22,color:C.ink,backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:15,padding:14}});
