import { useCallback, useMemo, useState } from 'react';
import { useFocusEffect, useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ScrollView, Share, StyleSheet, Text, TextInput, View } from 'react-native';
import { Body, Button, C, Card, Eyebrow, H1, H2, Page } from '@/components/ui';
import { OPERATORS } from '@/data/operators';
import { exportUatCsv, loadFeedback, loadUatSessions, UatFeedback, UatSession, uatMetrics } from '@/lib/uat';
import { birthBehaviorAgreement, confusionMatrix, exportResearchCsv, loadParticipants, loadTrials, makeResearchId, ResearchParticipant, ResearchTrial, researchMetrics, saveParticipant } from '@/lib/research';

export default function Research(){
 const router=useRouter(); const [uatSessions,setUatSessions]=useState<UatSession[]>([]); const [feedback,setFeedback]=useState<UatFeedback[]>([]); const [participants,setParticipants]=useState<ResearchParticipant[]>([]); const [trials,setTrials]=useState<ResearchTrial[]>([]); const [code,setCode]=useState(''); const [birth,setBirth]=useState(''); const [observed,setObserved]=useState('');
 const refresh=useCallback(()=>{Promise.all([loadParticipants(),loadTrials(),loadUatSessions(),loadFeedback()]).then(([p,t,u,f])=>{setParticipants(p);setTrials(t);setUatSessions(u);setFeedback(f)})},[]);
 useFocusEffect(useCallback(()=>{refresh()},[refresh]));
 const metrics=researchMetrics(trials); const um=uatMetrics(uatSessions); const matrix=useMemo(()=>confusionMatrix(trials),[trials]); const agreement=birthBehaviorAgreement(participants);
 const add=async()=>{const b=Number(birth);const o=Number(observed);if(!code.trim())return;await saveParticipant({id:makeResearchId('p'),code:code.trim(),createdAt:new Date().toISOString(),birthRoot:b>=1&&b<=9?b:null,observedOperator:o>=1&&o<=9?o:null});setCode('');setBirth('');setObserved('');refresh();};
 const shareCsv=async()=>{const csv=exportResearchCsv(participants,trials);await Share.share({message:csv,title:'PAA V0.8 anonymized research export'});};
 return <SafeAreaView style={{flex:1,backgroundColor:C.bg}}><ScrollView><Page>
   <Eyebrow>RESEARCH ENGINE · V0.8 RC1</Eyebrow><H1>Make the theory answer to records.</H1>
   <Body muted>Participants use study codes rather than names. Trials preserve pre-outcome predictions, whether the predictor was blinded, and the later observed operator.</Body>
   <Card><Eyebrow>UAT RELEASE CANDIDATE</Eyebrow><H2>{um.completed}/{um.assessmentStarted} core readings completed</H2><Body muted>{uatSessions.length} tester sessions · {feedback.length} feedback reports · {um.assessmentStarted?Math.round(um.completionRate*100):0}% assessment completion among starters.</Body><Button secondary label="Export UAT sessions + feedback" onPress={async()=>Share.share({message:exportUatCsv(uatSessions,feedback),title:'PAA V0.8 UAT export'})}/></Card>
   {feedback.slice(0,3).map(f=><Card key={f.id}><Eyebrow>UAT · {f.kind.toUpperCase()} · {f.screen}</Eyebrow><Body>{f.message}</Body><Body muted>{f.participantCode??'anonymous'} · {new Date(f.createdAt).toLocaleDateString()}</Body></Card>)}
   <View style={s.grid}><Card><Eyebrow>ALL TRIALS</Eyebrow><Text style={s.big}>{metrics.total}</Text><Body muted>{metrics.open} open</Body></Card><Card><Eyebrow>EXACT ACCURACY</Eyebrow><Text style={s.big}>{metrics.resolved?Math.round(metrics.exactAccuracy*100):0}%</Text><Body muted>{metrics.exact}/{metrics.resolved} scorable</Body></Card></View>
   <Card><Eyebrow>BLINDED SUBSET</Eyebrow><H2>{metrics.blindedResolved?Math.round(metrics.blindedAccuracy*100):0}% exact</H2><Body muted>{metrics.blindedResolved} resolved blinded trials. This is the harder subset: the predictor did not know the outcome when committing the forecast.</Body></Card>
   <Card><Eyebrow>BIRTH GLYPH ↔ OBSERVED BEHAVIOR</Eyebrow><H2>{agreement.eligible?Math.round(agreement.rate*100):0}% agreement</H2><Body muted>{agreement.matches}/{agreement.eligible} participants currently have both fields recorded. Agreement is descriptive; it does not establish causation or validity.</Body></Card>
   <Card><Eyebrow>ADD PARTICIPANT</Eyebrow><Body muted>Use an anonymous code such as P001. Birth root and observed operator are optional.</Body><TextInput value={code} onChangeText={setCode} placeholder="Participant code" placeholderTextColor={C.muted} style={s.input}/><TextInput value={birth} onChangeText={setBirth} placeholder="Birth root 1–9 (optional)" placeholderTextColor={C.muted} keyboardType="numeric" style={s.input}/><TextInput value={observed} onChangeText={setObserved} placeholder="Observed operator 1–9 (optional)" placeholderTextColor={C.muted} keyboardType="numeric" style={s.input}/><Button label="Create participant" onPress={add}/></Card>
   {participants.map(p=><Card key={p.id}><Eyebrow>PARTICIPANT {p.code}</Eyebrow><Body>Birth root: {p.birthRoot??'—'} · Observed: {p.observedOperator??'—'}</Body><Button secondary label="New blinded trial" onPress={()=>router.push({pathname:'/trial',params:{participantId:p.id}})}/></Card>)}
   <Card><Eyebrow>TRIAL LEDGER</Eyebrow><Body muted>Open trials can be resolved only after the outcome is observed. Resolved trials remain frozen for cohort analysis.</Body></Card>
   {trials.map(t=>{const p=participants.find(x=>x.id===t.participantId);const op=OPERATORS[t.predictedOperator-1];return <Card key={t.id}><Eyebrow>{t.resolvedAt?'RESOLVED':'OPEN'} · {p?.code??'UNKNOWN'} · {t.blinded?'BLINDED':'UNBLINDED'}</Eyebrow><H2>{t.predictedOperator} · {op.verb}</H2><Body muted>Source: {t.predictionSource} · Confidence {t.confidence}/5{t.actualOperator?` · Observed ${t.actualOperator}`:''}</Body>{!t.resolvedAt&&<Button secondary label="Resolve trial" onPress={()=>router.push({pathname:'/trial',params:{id:t.id,participantId:t.participantId}})}/>}</Card>})}
   <Card><Eyebrow>9 × 9 CONFUSION MATRIX</Eyebrow><Body muted>Rows are predicted operators; columns are observed operators. Diagonal cells are exact hits. Off-diagonal cells reveal which operators PAA systematically confuses.</Body><ScrollView horizontal><View>{<View style={s.matrixRow}><Text style={s.matrixHead}>P\A</Text>{OPERATORS.map(o=><Text key={o.n} style={s.matrixHead}>{o.n}</Text>)}</View>}{matrix.map((row,r)=><View key={r} style={s.matrixRow}><Text style={s.matrixHead}>{r+1}</Text>{row.map((v,c)=><Text key={c} style={[s.cell,v>0&&{fontWeight:'800',color:r===c?C.teal:C.wine}]}>{v}</Text>)}</View>)}</View></ScrollView></Card>
   <Button label="Export anonymized CSV" onPress={shareCsv}/><Button secondary label="Prospective prediction ledger" onPress={()=>router.push('/predictions')}/><Button secondary label="Return home" onPress={()=>router.replace('/')}/>
 </Page></ScrollView></SafeAreaView>
}
const s=StyleSheet.create({grid:{gap:12},big:{fontSize:42,fontWeight:'800',color:C.gold},input:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:14,padding:14,fontSize:16,color:C.ink},matrixRow:{flexDirection:'row'},matrixHead:{width:40,paddingVertical:8,textAlign:'center',fontWeight:'800',color:C.ink},cell:{width:40,paddingVertical:8,textAlign:'center',color:C.muted}});
