import { useEffect, useState } from 'react';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Body, Button, C, Card, Eyebrow, H1, Page } from '@/components/ui';
import { OPERATORS } from '@/data/operators';
import { loadParticipants, loadTrials, makeResearchId, PredictionSource, ResearchParticipant, ResearchTrial, resolveTrial, saveTrial } from '@/lib/research';

function Picker({value,onChange}:{value:number|null;onChange:(n:number)=>void}){return <View style={s.ops}>{OPERATORS.map(o=><Pressable key={o.n} onPress={()=>onChange(o.n)} style={[s.op,value===o.n&&s.active]}><Text style={[s.opText,value===o.n&&{color:C.white}]}>{o.n}</Text></Pressable>)}</View>}
export default function Trial(){
 const {participantId,id}=useLocalSearchParams<{participantId?:string;id?:string}>();const router=useRouter();const [participant,setParticipant]=useState<ResearchParticipant|null>(null);const [existing,setExisting]=useState<ResearchTrial|null>(null);const [pred,setPred]=useState<number|null>(null);const [source,setSource]=useState<PredictionSource>('researcher');const [confidence,setConfidence]=useState<1|2|3|4|5>(3);const [rationale,setRationale]=useState('');const [actual,setActual]=useState<number|null>(null);const [ambiguous,setAmbiguous]=useState(false);const [note,setNote]=useState('');
 useEffect(()=>{loadParticipants().then(ps=>setParticipant(ps.find(p=>p.id===participantId)||null));if(id)loadTrials().then(ts=>setExisting(ts.find(t=>t.id===id)||null));},[participantId,id]);
 if(id&&existing){return <SafeAreaView style={{flex:1,backgroundColor:C.bg}}><ScrollView><Page><Eyebrow>RESOLVE RESEARCH TRIAL</Eyebrow><H1>The prediction is already frozen.</H1><Card><Body>Predicted {existing.predictedOperator} · {OPERATORS[existing.predictedOperator-1].verb}</Body><Body muted>Source: {existing.predictionSource} · Confidence {existing.confidence}/5 · Blinded: {existing.blinded?'yes':'no'}</Body></Card><Eyebrow>OBSERVED OPERATOR</Eyebrow><Picker value={actual} onChange={n=>{setActual(n);setAmbiguous(false)}}/><Pressable onPress={()=>{setAmbiguous(!ambiguous);if(!ambiguous)setActual(null)}} style={[s.amb,ambiguous&&{backgroundColor:C.wine}]}><Text style={{fontWeight:'700',color:ambiguous?C.white:C.ink}}>Evidence is genuinely ambiguous</Text></Pressable><TextInput value={note} onChangeText={setNote} placeholder="Resolution note" placeholderTextColor={C.muted} multiline style={[s.input,{minHeight:100}]}/><Button label="Freeze outcome" onPress={async()=>{if(!actual&&!ambiguous)return;await resolveTrial(existing.id,actual,ambiguous,note);router.replace('/research')}}/></Page></ScrollView></SafeAreaView>}
 return <SafeAreaView style={{flex:1,backgroundColor:C.bg}}><ScrollView><Page><Eyebrow>BLINDED RESEARCH TRIAL</Eyebrow><H1>Commit before the outcome is known.</H1><Body muted>Participant: {participant?.code??'unknown'}. This screen intentionally does not display the participant's recorded observed operator while the forecast is being made.</Body><Eyebrow>PREDICTED OPERATOR</Eyebrow><Picker value={pred} onChange={setPred}/><Eyebrow>PREDICTION SOURCE</Eyebrow><View style={s.sources}>{(['birth','boi','researcher','other'] as PredictionSource[]).map(x=><Pressable key={x} onPress={()=>setSource(x)} style={[s.source,source===x&&s.active]}><Text style={{fontWeight:'700',color:source===x?C.white:C.ink}}>{x.toUpperCase()}</Text></Pressable>)}</View><Eyebrow>CONFIDENCE</Eyebrow><View style={s.ops}>{[1,2,3,4,5].map(n=><Pressable key={n} onPress={()=>setConfidence(n as any)} style={[s.op,confidence===n&&s.active]}><Text style={[s.opText,confidence===n&&{color:C.white}]}>{n}</Text></Pressable>)}</View><TextInput value={rationale} onChangeText={setRationale} placeholder="Rationale / warrant" placeholderTextColor={C.muted} multiline style={[s.input,{minHeight:100}]}/><Button label="Commit blinded trial" onPress={async()=>{if(!participantId||!pred)return;const record:ResearchTrial={id:makeResearchId('t'),participantId,createdAt:new Date().toISOString(),predictedOperator:pred,predictionSource:source,confidence,blinded:true,rationale:rationale.trim()};await saveTrial(record);router.replace('/research')}}/></Page></ScrollView></SafeAreaView>
}
const s=StyleSheet.create({ops:{flexDirection:'row',flexWrap:'wrap',gap:8},op:{width:44,height:44,borderRadius:22,borderWidth:1,borderColor:C.line,alignItems:'center',justifyContent:'center',backgroundColor:C.white},active:{backgroundColor:C.lapis,borderColor:C.lapis},opText:{fontWeight:'800',color:C.ink},sources:{flexDirection:'row',flexWrap:'wrap',gap:8},source:{paddingHorizontal:12,paddingVertical:10,borderRadius:12,borderWidth:1,borderColor:C.line,backgroundColor:C.white},input:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:14,padding:14,fontSize:16,color:C.ink,textAlignVertical:'top'},amb:{padding:14,borderRadius:14,borderWidth:1,borderColor:C.line,backgroundColor:C.white}});
